# Generated by Django 3.2 on 2024-04-09 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "registration_open",
                    models.BooleanField(verbose_name="Регистрация открыта"),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "head_image",
                    models.ImageField(
                        upload_to="events/images/head_images/",
                        verbose_name="Основное изображение",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "video_link",
                    models.URLField(max_length=256, verbose_name="Видео линк"),
                ),
            ],
            options={
                "verbose_name": "Ивент",
                "verbose_name_plural": "Ивенты",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Формат",
                "verbose_name_plural": "Формат",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.specialization",
                        verbose_name="Направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стэк",
                "verbose_name_plural": "Стэк",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Темы",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StackEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.stack",
                        verbose_name="Стэк",
                    ),
                ),
            ],
            options={
                "ordering": ("event",),
            },
        ),
        migrations.CreateModel(
            name="SpecializationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.specialization",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "ordering": ("event",),
            },
        ),
        migrations.AddField(
            model_name="specialization",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="events.theme",
                verbose_name="Тема",
            ),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(max_length=256, verbose_name="Должность"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="events/images/speakers_photos/"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
            ],
            options={
                "ordering": ("event",),
            },
        ),
        migrations.CreateModel(
            name="Program_part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Ивент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часть программы",
                "verbose_name_plural": "Части программы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ParticipantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participate_online",
                    models.BooleanField(verbose_name="Участвую онлайн"),
                ),
                (
                    "areement_events",
                    models.BooleanField(verbose_name="Соглашаюсь получать приглашения"),
                ),
                (
                    "areement_vacancies",
                    models.BooleanField(verbose_name="Соглашаюсь получать вакансии"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participated_events",
                        to="events.event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participated_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участник ивента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник Ивента",
                "verbose_name_plural": "Участники Ивентов",
                "ordering": ("event",),
            },
        ),
        migrations.CreateModel(
            name="Galery_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/images/galery_images/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение для галереи",
                "verbose_name_plural": "Галерея изображений",
                "ordering": ("event",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.form",
                verbose_name="Формат",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                through="events.ParticipantEvent", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="specialization",
            field=models.ManyToManyField(to="events.Specialization"),
        ),
        migrations.AddField(
            model_name="event",
            name="stack",
            field=models.ManyToManyField(to="events.Stack"),
        ),
        migrations.AddField(
            model_name="event",
            name="town",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.town",
                verbose_name="Город",
            ),
        ),
    ]
